### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by amazinn** [ultratype/UltraTypeBot#1]
There is a bug where it stops typing after a few words, then I type for it and my car doesn't move or anything then I get kicked for idle.

**Comment by ultratype** [comment]
I have just tested this myself. This only happens if you are not focused on the tab/window the bot is running in. I can not fix this issue due to how Chrome/Chromium manages inactive browser tabs/windows. When you are using UltraType, please make sure your tab with the bot is kept active for it to continue typing.
