### ISSUE TITLE
Way to select a range for WPM/Accuracy

### ISSUE THREAD

**Issue by patoaravena** [ultratype/UltraTypeBot#2]
FIrst of all, GREAT JOB! This extension is very handy.
Now, I notice that many users get banned for using it, since it simulates a high level of accuracy, which the servers can pick up as a pattern. It would be nice if there is a way set random levels of accuracy/WPM that can alternate so NitroType will not get too suspicious. 

Thanks,

**Comment by SandvichPolice** [comment]
As my review and what "patoaravena" said summed it up. You should make it so you choose 2 numbers and it chooses a random number for the wpm every race. Besides that, this is basically perfect!

**Comment by ultratype** [comment]
I will look at the source of the bans, and I will definitely consider this. Thank you

**Comment by SandvichPolice** [comment]
Wait, so now is there also a way to select a range for wpm? Also a good idea might be able to set a range for wpm and accuracy.

**Comment by ultratype** [comment]
I've decided not to implement this, and just review the NitroType game client. The reason I'm not going to implement this feature is because many of the people that use my extension don't really want to have to go through the trouble of messing with the settings, and instead just be able to install the extension and race. I feel that a complex options menu will drive users away from my simplistically designed extension.

**Comment by ultratype** [comment]
I just released a new version of the extension, please try it out, preferably on an alt account,
